### ISSUE TITLE
Suggestions and Bugs

### ISSUE THREAD

**Issue by Ravenclaw5874** [urakagi/uma-clock-emu#45]
1st Anni : uma-2 branch
2nd Anni : master branch

Suggestions

1. Inherit of あっぱれ大盤振る舞い！ is categorized Accel skill on 1st Anni, Speed and Accel skill on 2nd Anni. Unify?

2. 優等生×バクシン＝大勝利ッ and Fairy tale is same skill with only different order condition. But has different activation section on emu. Unify?

3. In 2nd Anni, 最強の名を懸けて will be more accurate when change condition from final straight random to phase 2 final corner random. I'm not sure about 1st Anni.

4. is_overtake==1 Unique Skills.
Random : Nemesis / 薫風、永遠なる瞬間を / コンドル猛撃波
Immediately : 白い稲妻、見せたるで / KEEP IT REAL.
These skills have same condition is_overtake==1, but some are random and some are immediate.
I think it would be more accurate to unify it to random.

5. Course limited Unique skills
威風堂々、夢錦！ : 中山 limit
α-star* : ダート limit
-> These Unique skills are activated with reinforced performance even in places not 中山/ダート
アゲてアゲてぷちょへんざ！ : 短距離/マイル limit
あなたに捧げるフリーポア : 中距離 limit
Never say Never : ダート limit
-> These Unique skills are not activated anywhere else.
Wondering if you're willing to process to trigger on basic or enhanced performance anywhere else.

Bugs in 1st Anniversary Emulator only (uma-2 branch)

1. Skills that doesn't exist
光芒円刃
いいとこ入った！
仕掛け準備
準備万全！
ライトニングステップ
イナズマステップ
熱いまなざし
あやしげな作戦
博打うち
熱血！！風紀アタック
Adventure of 564

2. Skills that doesn't activate
圧倒的リード
大きなリード
春一番
初嵐
ナイター◎
ナイター○

3. Inherit of かがやけ☆とまこまい doesn't show when 差し, 追込 even if ダート course. (It shows every running style in 2nd Anni)

4. Joyful Voyage!'s speedWithDecel is ignored. (not ignored in 2nd Anni). Never Say Never is normal.

5. 灯穂 is activated in phase 2 corner, not final straight. (normal in 2nd Anni)
It's actual targetSpeed is 0.385 in emu, but written 0.35として扱う in tooltip.
Inherit of 灯穂's targetSpeed is written 0.19 in tooltip. Don't know actual value in emu.

6. Inherit of 灰色の臨界点's targetSpeed is written 0.35 in tooltip. It should be 0.15 (normal in 2nd Anni). Don't know actual value in emu.

7. Inherit of Ding Dong Boo shows on everywhere. (It only shows on ダート in 2nd Anni)

8. 気迫を込めて/荒ぶる旋風 are activated immediately when race start. It should be phase 1 random.

9. 技巧派/巧みなステップ has 1.8sec duration. It should be 3sec after 1st Anni.

10. 先陣の心得/リードキープ's tooltip says it has 3馬身 condition. It shuold be 1馬身 after 1st Anni.

11. 勝利への執念/食い下がり/電撃の煌めき/詰め寄り are Speed and Accel skills after 1st Anni, but it's not in emu.

12. トップランナー and 先頭プライド's activation section are different. It will be great to unify phase_laterhalf_random: 0 like 2nd Anni emu.

13. 出力1000％！/しゃかりき's activation section is phase_laterhalf_random: 1. It should be phase_firsthalf_random: 1 like 2nd Anni emu.

Bugs in 1st&2nd Anniversary Emulator (uma-2 & master branch)

1. Skills that doesn't exist
くじけぬ精神

2. Skills that doesn't activate
萌到讓我活過來了！

3. In courses that doesn't have uphill or downhill (ex. 札幌), emulator crashes when uphill/downhill skills activated.
uphill/downhill skills : 百万バリキ / 十万バリキ / 至高のダウンヒラー / 下り坂巧者 / 決意の直滑降 / 直滑降 / 登山家
error log : 
Uncaught TypeError: Cannot read properties of undefined (reading 'start')
    at o.initSlopeRandom (MixinSkills.vue:643:46)
    at o.checkCondition (MixinSkills.vue:328:23)
    at o.initSkillConditions (MixinSkills.vue:450:1)
    at o.invokeSkills (MixinSkills.vue:255:18)
    at o.start (MixinRaceCore.vue:527:12)
    at MixinRaceCore.vue:511:1

4. きっとその先へ…！ is phase 3 random, not phase 2 random. Is this correct?
シューティングスター / 来ます来てます来させます！ / 尊み☆ﾗｽﾄｽﾊﾟ━━(ﾟ∀ﾟ)━━ﾄ! are phase 2 random.

6. Ding Dong Boo is activated Immediately. It should be final straight random like 快走かな、快走かな！

7. きらめくは海、まばゆきは君 / 麗しき花信風 's duration increases with each simulation.
Ex) 新潟 1000m. 1000/3000/1000/1000/1000. 全乱数固定
It seems that duration multiplier is not reseted properly on each simulation.

8. ときめきが呼ぶほうへ is activated in phase 2 downhill too (ex. 京都 3000m).
It should be activated in phase 1 downhill only.

9. 絶対は、ボクだ has buffed to 0.45 speed skill in 1st Anni, but 0.35 speed skill in 1st & 2nd Anni emu.

10. 灰色の臨界点 has unnecessary 400m condition.

11. 30sec cooldown skills.
confirmed to activate twice : コーナー巧者○ / 弧線のプロフェッサー / コーナー加速○ / 曲線のソムリエ
can't activated twice : 直線巧者 / ハヤテ一文字 / 直線加速 / 一陣の風
emulator set phase 1 random, so not activated twice because of cooldown doesn't finished : スリップストリーム / いいとこ入った！ / 遊びはおしまいっ！ / お先に失礼っ！
actual phase 1 random in-game : ペースアップ / アガッてきた！
I think 直線巧者 / ハヤテ一文字 / 直線加速 / 一陣の風 should be able to activate twice.

12. 気迫を込めて / 荒ぶる旋風 / スピードグリード / スピードイーター 's order condition is 1~3, but running style limited to 逃げ only. How about to add 先行?

13. アオハル燃焼・速 / アオハル点火・速's multiplier is 1.15. But In game, it should be 1.1 or 1.2. Why 1.15?

14. typing error : Schwarze Schwert -> Schwarzes Schwert

15. triggerRate of やまっけ should be 0.3 when popularity>=4, not 0.6.

Bugs in 2nd Anniversary Emulator only (master branch)
1. Inherit of Do Ya Breakin!'s tooltip says it's acceleration is 0.05. It should be 0.07 after 2nd Anni. Don't know actual value in emu.

2. アクセル全開！ / アクセラレーション are activated immediatly when race start. It should be phase 1 random.

3. 出力1000％！ / しゃかりき are stamina -400 and speed skill but categorized speed skill in 2nd Anni emu.
勇往邁進 is normal.

4. 博打うち / あやしげな作戦 's rarity is swapped. 博打うち = rare , あやしげな作戦 = normal.

5. 博打うち / あやしげな作戦 activate どこ吹く風 / ウマ込み冷静 and not activate itself on simulation.

6. I'm not sure, but Max of 熱血！！風紀アタック isn't 0.4 accel 5 duration (inherit : 0.2 accel 2.7 duration)?

**Comment by urakagi** [comment]
熱血！！風紀アタック and Adventure of 564 won't be implemented in uma-2. (Too complicated with uma-2 structure)

**Comment by urakagi** [comment]
Bugs in uma-2 fixed and updated to beta site.

**Comment by urakagi** [comment]
Bugs in master fixed except 出力1000％！ / しゃかりき in speed is meant to be, 勇往邁進 was wrong and fixed.
Also, 熱血！！風紀アタック is just implemented haphazardly because it's seriously troublesome.

**Comment by urakagi** [comment]
Bugs in uma-2 & master branch are fixed and uploaded to both sites except:
- きっとその先へ in phase 3 is meant to be (due to the condition)
- 直線巧者 / ハヤテ一文字 / 直線加速 / 一陣の風 is straight_random, In my understanding it's is only one point so it won't trigger twice. If you have counterproof please let me know.
- スリップストリーム etc. trigger twice won't be implemented since it's complicated and not important.
- アオハル速度's 1.15 is sort of an average of 1.1 (Not all 1200 or debuff included) and 1.2 (all 1200).
- I am too lazy to seperate the trigger rate of やまっけ and 勝負師. Who are using these skills?

**Comment by urakagi** [comment]
For suggestions:
1,2,3: fixed
4: Besides 白い稲妻 fixed, but 白い稲妻 need to be immediately since it's special condition.
5: Enforcements require master branch code changes, so in uma-2 only the most used case will be implemented (and for all conditions)

**Comment by urakagi** [comment]
@Ravenclaw5874 
I am closing this issue since codes are updated, please open another issue for things still wrong after the update.
Thank you very much.
