### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by Ravenclaw5874** [urakagi/uma-clock-emu#46]
Thank you for fast support.
Here's some new bugs.

KEEP IT REAL. 
uma-2 (bug) condition is changed to finalcorner random. In-game condition is distance_rate>=50 &is_overtake==1
master : condition is distance_rate>=50 Immediate.

最強の名を懸けて
uma-2 (normal)
master (bug) crashes when emulation.
error log : Uncaught TypeError: Cannot read properties of undefined (reading 'randoms')
    at check (skillData.js:6064:35)
    at e.check (MixinSkills.vue:462:1)
    at o.checkSkillTrigger (MixinSkills.vue:510:1)
    at o.progressRace (MixinRaceCore.vue:669:1)
    at o.start (MixinRaceCore.vue:539:12)
    at MixinRaceCore.vue:511:1

いいとこ入った！
uma-2 (bug) typing error : いいとこ入った -> いいとこ入った！
master (normal)

ライトニングステップ / イナズマステップ
uma-2 (bug) name swapped. rare : ライトニングステップ / normal : イナズマステップ
master (normal)

Inherit of かがやけ☆とまこまい
uma-2 (bug) show on Turf and Dirt
master (normal) show on Dirt

トップランナー / 先頭プライド
uma-2 (bug) activation section of トップランナー changed to 9~25% random, but 先頭プライド doesn't. Unify?
master both are phase_laterhalf_random: 0

出力1000％！ / しゃかりき / 勇往邁進
uma-2 categorized as 複合
master categorized as 速度
Unify?

Uphill & Downhill Skills
List : 百万バリキ / 十万バリキ / 至高のダウンヒラー / 下り坂巧者 / 決意の直滑降 / 直滑降 / 登山家
uma-2 (normal)
master (bug) In course doesn't have uphill or downhill (ex. 札幌), activate immediately with race start. It should not activate.

Ding Dong Boo
uma-2 & master : condtion is final straight immediate, while 快走かな、快走かな！ is final straight random. Unify?

ときめきが呼ぶほうへ
uma-2 & master : activate in phase 2 downhill also (ex. 京都 3000m). It should be activated in phase 1 downhill only.

**Comment by urakagi** [comment]
Fixed and updated other than 出力1000％！won't be unified since it's a strcuture change of master.
