### ISSUE TITLE
Request of latestRaceTime format

### ISSUE THREAD

**Issue by Ravenclaw5874** [urakagi/uma-clock-emu#52]
Since race time does not follow a specific distribution when skill activated, I'm developing an extension that records every latestRaceTime when emulation.
latestRaceTime is taken from "直近レース詳細(2:32.10)", so it is difficult to obtain an accurate value because it is formated in 2 below decimal point.
Would you consider changing formatTime(latestRaceTime, **2->3**) in ChampMeet.vue (+ TeamRace.vue)?
Thank you.

**Comment by urakagi** [comment]
I can't understand what you want to do? If you just want to change the decimal from 2 to 3, I'm OK with it so just create a PR for it.

**Comment by Ravenclaw5874** [comment]
Ok, I will. Thank you.
