### ISSUE TITLE
 Do Ya Breakin! 在longchamp 2400的功能不正確

### ISSUE THREAD

**Issue by panis013** [urakagi/uma-clock-emu#66]
longchamp 2400的1617-1866假直綫 type不是2 
不應該觸發 Do Ya Breakin!的加速度版本

**Comment by urakagi** [comment]
真的假的🥲
我晚上有空再確認一下資料

**Comment by urakagi** [comment]
確認了是假直線是直線沒有錯
請問是實際上確認了 Do Ya Breakin! 沒有加速度效果嗎？
