### ISSUE TITLE
Inherit かがやけ☆とまこまい, 風光る has wrong accel

### ISSUE THREAD

**Issue by Ravenclaw5874** [urakagi/uma-clock-emu#67]
Inherit version of かがやけ☆とまこまい has no additional effect, so it should be 0.07. It is 0.2 in uma2 and master now.
Inherit version of 風光る should be 0.07 when order==2. It is 0.2 in uma2, 0.05 in master.

**Comment by urakagi** [comment]
https://github.com/urakagi/uma-clock-emu/commit/a3176b3c9182d916b75c80f79a9d8d468d1447c2
