### ISSUE TITLE
Course length doesn't contain 外, 内 in uma2 and master

### ISSUE THREAD

**Issue by Ravenclaw5874** [urakagi/uma-clock-emu#68]
![course](https://github.com/urakagi/uma-clock-emu/assets/10994248/29e7033c-407d-49a6-847c-fc55db2a2581)

In course_data.json, 外, 内 are included, but these are doesn't show in website.

So we can't distinguish 京都 芝1400m, 芝1600m, 新潟 芝2000m.

**Comment by urakagi** [comment]
Fixed in https://github.com/urakagi/uma-clock-emu/commit/a3176b3c9182d916b75c80f79a9d8d468d1447c2
